### ISSUE TITLE
All entities are unavailable after update

### ISSUE THREAD

**Issue by adamchemiawppl** [ScratMan/HASmartThermostat#209]
**Describe the bug**
After update all entities are missing/unavailable

**To Reproduce**
Update working setup 2023.9 to 2023.10 or 2024.2

**Expected behavior**
After updating from 2023.9 to 2023.10 or 2024.2 my configuration stopped working. I read through readme and changelog - but found no indication of any breaking changes or any adjustments I'm expected to make.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 121.0.6167.185

**Comment by ScratMan** [comment]
Could you please provide some logs ?

**Comment by dexteria01** [comment]
Hi,

I am having the same issue, updated Smart Thermostat (PID) in HACS and it stopped working. I'm using HA in docker, 2024.2

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:360
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 16:37:21 (4 occurrences)
Last logged: 16:37:21

Error while setting up smart_thermostat platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/smart_thermostat/climate.py", line 192, in async_setup_platform
    smart_thermostat = SmartThermostat(**parameters)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smart_thermostat/climate.py", line 288, in __init__
    self._support_flags |= ClimateEntityFeature.TURN_OFF
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF

![image](https://github.com/ScratMan/HASmartThermostat/assets/97369838/16320f0c-5b5a-4817-8218-753193a55507)


thanks

Mark

**Comment by ScratMan** [comment]
It looks like it misses the ClimateEntityFeature from HA core. What are your Home Assistant release versions ?
It seems this part is new in 2024.2.0

**Comment by Edo78** [comment]
I just noticed this issue with `2024.1.5`
