### ISSUE TITLE
control_output above output_max

### ISSUE THREAD

**Issue by vasyna** [ScratMan/HASmartThermostat#258]
**Describe the bug**
set output_min = 0 and output_max = 5, but when worked termostat set control_output above 5. Because of this there is no control over the heater.

config:
```
climate:
  - platform: smart_thermostat
    name: Cauldron termostat
    unique_id: cauldron_termostat
    heater: number.boiler_operating_mode
    target_sensor: sensor.home_temperature
    outdoor_sensor: sensor.esp_01_yard_rear_temperature
    min_temp: 15
    max_temp: 30
    ac_mode: False
    target_temp: 25
    keep_alive:
      seconds: 60
    pwm: 0
    kp: 50
    ki: 0.01
    kd: 2000
    ke: 0.6
    #output_safety: 3
    output_min: 0
    output_max: 5
    output_precision: 0
```

number.boiler_operating_mode a number with limits from 0 to 5.

**Screenshots**
![image](https://github.com/user-attachments/assets/8ab7ef9b-6660-4f8b-a3f9-fbed9526b8c3)

Error
```
Регистратор: homeassistant.core
Источник: core.py:2822
Первое сообщение: 12:42:31 (13 сообщений)
Последнее сообщение: 12:46:08

Error executing service: <ServiceCall number.set_value (c:01JC5JHVABHA4NNV39FJPRRP5E): entity_id=['number.boiler_operating_mode'], value=37.0>
Error executing service: <ServiceCall number.set_value (c:01JC5JKFHJ099HSXN7NHJ903CN): entity_id=['number.boiler_operating_mode'], value=37.0>
Error executing service: <ServiceCall number.set_value (c:01JC5JKJVX918K8CQ0716G5463): entity_id=['number.boiler_operating_mode'], value=37.0>
Error executing service: <ServiceCall number.set_value (c:01JC5JNA4QFCCCK7VZS6X01CCB): entity_id=['number.boiler_operating_mode'], value=37.0>
Error executing service: <ServiceCall number.set_value (c:01JC5JNDEYQ3V6CG85W9157RJ8): entity_id=['number.boiler_operating_mode'], value=37.0>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 105, in async_set_value
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: Value 42.0 for number.boiler_operating_mode is outside valid range 0.0 - 5.0
```

**Comment by ScratMan** [comment]
Please try by also adding `out_clamp_high: 5.0` in the configuration of the thermostat.

**Comment by vasyna** [comment]
> Please try by also adding `out_clamp_high: 5.0` in the configuration of the thermostat.

Thank you. It helped. I even think it works better.
